services:
  app:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    networks:
      - duck_link
  db:
    container_name: duck_link_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - duck_link

volumes:
  db_data:

networks:
  duck_link:
    driver: bridge